from .cli import main
from .css import DEMO_CSS
from .model import USER_MODEL
from .settings import APP_SETTINGS
from .cmd_handler import CmdHandler
from .html import BASE_HTML, FLASH_MESSAGE, DEMO_HTML_TEMPLATES
from .routes_ import (
    GITIGNORE,
    APP_STARTUP,
    ACCOUNT_UTILS,
    SEARCH_FORM_DATA,
    UPLOAD_FILES_FORM,
    VIEW_TEMPLATE_CODE,
    ADMIN_TEMPLATE_CODE,
    SEARCH_TEMPLATE_CODE,
    ACCOUNT_SETTINGS_FORM,
    ACCOUNT_SETTINGS_FORM,
    UPLOAD_FILES_TEMPLATE_CODE,
    ERROR_HANDLER_TEMPLATE_CODE,
    AUTHENTICATION_TEMPLATE_CODE,
    ACCOUNT_SETTINGS_TEMPLATE_CODE,
)
