from .cli import main
from .model import USER_MODEL
from .settings import APP_SETTINGS
from .cmd_handler import CmdHandler
from .env import ENVIRONMENT_VARIABLE
from .js import LOG_JS, SADASHBOARD_JS
from .css import LOG_CSS, SADASHBOARD_CSS, FLASH_MESSAGE
from .forms import (
    AUTHENTICATION_FORM,
    SADASHBOARD_FORM,
    ACCOUNT_SETTINGS_FORM,
    UPLOAD_FILES_FORM,
    SEARCH_FORM,
)
from .html import (
    BASE_HTML,
    FLASH_CUSTOM_HTML,
    SADASHBOARD_SECURE,
    SADMIN_LOGIN_SECURE,
    DEMO_HTML_TEMPLATES,
    AUTHENTICATION_LOGIN_HTML,
    AUTHENTICATION_REGISTER_HTML,
)
from .routes_ import (
    GITIGNORE,
    APP_STARTUP,
    ACCOUNT_UTILS,
    CACHING_CONSTANT,
    VIEW_TEMPLATE_CODE,
    ADMIN_TEMPLATE_CODE,
    SEARCH_TEMPLATE_CODE,
    SUPER_ADMIN_DASHBOARD_,
    FILES_UPLOAD_TEMPLATE_CODE,
    ERROR_HANDLER_TEMPLATE_CODE,
    AUTHENTICATION_TEMPLATE_CODE,
    ACCOUNT_SETTINGS_TEMPLATE_CODE,
)
